// Mock data — used ONLY when VITE_USE_MOCK === "true".
// Production builds (VITE_USE_MOCK unset/false) always hit the real backend.

import type {
  Account, ActiveTrade, BotStatus, Channel, Notification,
  RiskProfile, TradeHistory,
} from "./types";

const now = Date.now();
const iso = (msAgo: number) => new Date(now - msAgo).toISOString();

export const mockAccounts: Account[] = [
  {
    account_key: "trader1@example.com:48721",
    credential_key: "trader1@example.com",
    tl_account_id: "48721",
    tl_email: "trader1@example.com",
    tl_server: "FTMO-Demo",
    tl_prop_firm: "FTMO",
    display_name: "FTMO 100K Challenge",
    initial_balance: 100000,
    current_balance: 102450.25,
    highest_banked_balance: 103200,
    all_time_high_equity: 103200,
    profit_locked: false,
    daily_pnl: 245.75,
    daily_start_balance: 102204.5,
    last_synced_balance: 102450.25,
    cycle_start_date: iso(86400000 * 14),
    cycle_best_day_pnl: 980,
    paused: false,
    breached: false,
    risk_profile_id: 1,
    max_concurrent_trades_override: null,
    lot_size_override: null,
    daily_drawdown_pct: 2.4,
    daily_loss_limit_pct: 5,
    overall_drawdown_pct: 2.45,
    overall_loss_limit_pct: 10,
    consistency_score: 72.5,
    profitable_days_count: 8,
    total_trading_days: 14,
    required_profitable_days: 5,
  },
  {
    account_key: "trader2@example.com:33910",
    credential_key: "trader2@example.com",
    tl_account_id: "33910",
    tl_email: "trader2@example.com",
    tl_server: "MFF-Live",
    tl_prop_firm: "MFF",
    display_name: "MFF Funded 50K",
    initial_balance: 50000,
    current_balance: 49120.4,
    highest_banked_balance: 50880,
    all_time_high_equity: 50880,
    profit_locked: true,
    daily_pnl: -120.6,
    daily_start_balance: 49241,
    last_synced_balance: 49120.4,
    cycle_start_date: iso(86400000 * 5),
    cycle_best_day_pnl: 410,
    paused: true,
    breached: false,
    risk_profile_id: 2,
    max_concurrent_trades_override: 3,
    lot_size_override: 0.5,
    daily_drawdown_pct: 4.8,
    daily_loss_limit_pct: 5,
    overall_drawdown_pct: 1.76,
    overall_loss_limit_pct: 10,
    consistency_score: null,
    profitable_days_count: 3,
    total_trading_days: 5,
    required_profitable_days: 5,
  },
  {
    account_key: "trader3@example.com:88412",
    credential_key: "trader3@example.com",
    tl_account_id: "88412",
    tl_email: "trader3@example.com",
    tl_server: "TFT-Demo",
    tl_prop_firm: "TFT",
    display_name: "TFT Phase 1",
    initial_balance: 25000,
    current_balance: 22100,
    highest_banked_balance: 25400,
    all_time_high_equity: null,
    profit_locked: false,
    daily_pnl: 0,
    daily_start_balance: 22100,
    last_synced_balance: 22100,
    cycle_start_date: iso(86400000 * 22),
    cycle_best_day_pnl: 220,
    paused: false,
    breached: true,
    risk_profile_id: 1,
    max_concurrent_trades_override: null,
    lot_size_override: null,
    daily_drawdown_pct: 0,
    daily_loss_limit_pct: 5,
    overall_drawdown_pct: 11.6,
    overall_loss_limit_pct: 10,
    consistency_score: 0,
    profitable_days_count: 2,
    total_trading_days: 22,
    required_profitable_days: 5,
  },
];

export const mockChannels: Channel[] = [
  {
    channel_id: -1001234567890,
    display_name: "Apex Signals",
    signal_prefix: "APEX",
    entry_logic_module: "logic.entry.standard",
    management_logic_module: "logic.manage.trail_be",
    priority: 10,
    enabled: true,
    notes: "Primary morning London session feed.",
  },
  {
    channel_id: -1009876543210,
    display_name: "NY Scalps",
    signal_prefix: "NYS",
    entry_logic_module: "logic.entry.scalp",
    management_logic_module: "logic.manage.tp1_partial",
    priority: 20,
    enabled: true,
    notes: null,
  },
  {
    channel_id: -1005554443332,
    display_name: "Swing Desk",
    signal_prefix: "SWG",
    entry_logic_module: "logic.entry.swing",
    management_logic_module: "logic.manage.runner",
    priority: 30,
    enabled: false,
    notes: "Paused pending review.",
  },
];

export const mockRiskProfiles: RiskProfile[] = [
  {
    profile_id: 1,
    profile_name: "Standard Funded",
    is_default: true,
    max_risk_per_trade_pct: 0.5,
    daily_loss_pct: 4,
    daily_trailing: true,
    overall_loss_pct: 8,
    overall_trailing: true,
    overall_trail_from_closed_balance: true,
    profit_lock_pct: 5,
    profit_lock_floor_pct: 2,
    payout_buffer_pct: 1,
    max_concurrent_trades: 5,
    commission_per_lot: 7,
    safety_buffer_pct: 0.5,
    notes: "Default profile for funded prop accounts.",
  },
  {
    profile_id: 2,
    profile_name: "Aggressive Phase 1",
    is_default: false,
    max_risk_per_trade_pct: 1.5,
    daily_loss_pct: 4.5,
    daily_trailing: false,
    overall_loss_pct: 9,
    overall_trailing: false,
    overall_trail_from_closed_balance: false,
    profit_lock_pct: null,
    profit_lock_floor_pct: null,
    payout_buffer_pct: 0.5,
    max_concurrent_trades: 8,
    commission_per_lot: 7,
    safety_buffer_pct: 0.25,
    notes: null,
  },
];

export const mockActiveTrades: ActiveTrade[] = [
  {
    trade_id: 9001,
    account_key: "trader1@example.com:48721",
    channel_id: -1001234567890,
    channel_name: "Apex Signals",
    signal_id: "APEX-2410",
    sub_signal_id: null,
    symbol: "EURUSD",
    direction: "BUY",
    entry_price: 1.08545,
    sl: 1.0834,
    tp: 1.0895,
    lot_size: 0.5,
    entry_time: iso(15 * 60000),
    tl_order_id: "ord-1",
    tl_position_id: "pos-1",
    status: "filled",
    tp1_hit: false,
    risk_usd: 102.5,
    current_pnl: 45.75,
  },
  {
    trade_id: 9002,
    account_key: "trader1@example.com:48721",
    channel_id: -1009876543210,
    channel_name: "NY Scalps",
    signal_id: "NYS-883",
    sub_signal_id: "B",
    symbol: "XAUUSD",
    direction: "SELL",
    entry_price: 2342.55,
    sl: 2349.0,
    tp: 2330.0,
    lot_size: 0.25,
    entry_time: iso(2 * 3600000 + 12 * 60000),
    tl_order_id: "ord-2",
    tl_position_id: "pos-2",
    status: "filled",
    tp1_hit: true,
    risk_usd: 161.25,
    current_pnl: -23.50,
  },
  {
    trade_id: 9003,
    account_key: "trader2@example.com:33910",
    channel_id: -1001234567890,
    channel_name: "Apex Signals",
    signal_id: "APEX-2411",
    sub_signal_id: null,
    symbol: "GBPJPY",
    direction: "BUY",
    entry_price: 198.245,
    sl: 197.8,
    tp: 199.1,
    lot_size: 0.3,
    entry_time: iso(42 * 60000),
    tl_order_id: "ord-3",
    tl_position_id: "pos-3",
    status: "filled",
    tp1_hit: false,
    risk_usd: 89.1,
    current_pnl: 12.30,
  },
];

const symbols = ["EURUSD", "GBPUSD", "USDJPY", "XAUUSD", "GBPJPY"];
const closeReasons = ["TP_HIT", "SL_HIT", "MANUAL", "EOD", "BREACH"];

export const mockTradeHistory: TradeHistory[] = Array.from({ length: 84 }).map(
  (_, i) => {
    const symbol = symbols[i % symbols.length];
    const dir: "BUY" | "SELL" = i % 2 === 0 ? "BUY" : "SELL";
    const entry = 1 + ((i * 13) % 200) / 1000;
    const pnl = ((i * 37) % 280) - 120;
    const outcome: "WIN" | "LOSS" | "BE" =
      pnl > 0 ? "WIN" : pnl < 0 ? "LOSS" : "BE";
    const manual = i % 11 === 0 ? "PARTIAL" : i % 17 === 0 ? "CLOSE" : null;
    return {
      history_id: 7000 + i,
      account_key:
        i % 3 === 0
          ? "trader1@example.com:48721"
          : i % 3 === 1
            ? "trader2@example.com:33910"
            : "trader3@example.com:88412",
      channel_id: i % 2 ? -1001234567890 : -1009876543210,
      channel_name: i % 2 ? "Apex Signals" : "NY Scalps",
      signal_id: `SIG-${7000 + i}`,
      sub_signal_id: null,
      symbol,
      direction: dir,
      entry_price: entry,
      exit_price: entry + (dir === "BUY" ? pnl / 10000 : -pnl / 10000),
      sl: entry - 0.002,
      tp: entry + 0.003,
      lot_size: 0.1 + (i % 5) * 0.1,
      entry_time: iso((i + 1) * 3600000),
      exit_time: iso(i * 3600000),
      pnl,
      outcome,
      close_reason: closeReasons[i % closeReasons.length],
      manual_action_type: manual as TradeHistory["manual_action_type"],
    };
  },
);

export const mockNotifications: Notification[] = [
  {
    notification_id: 5001,
    account_key: "trader1@example.com:48721",
    category: "EXECUTION",
    severity: "INFO",
    title: "Trade Opened: EURUSD",
    message: "Opened BUY 0.50 lots at 1.08545",
    metadata: { trade_id: 9001 },
    read: false,
    created_at: iso(3 * 60000),
  },
  {
    notification_id: 5002,
    account_key: "trader3@example.com:88412",
    category: "BREACH",
    severity: "CRITICAL",
    title: "Daily loss limit breached",
    message: "Account TFT Phase 1 hit -$2,900 daily loss. Trading suspended.",
    metadata: { account: "trader3@example.com:88412", loss: -2900 },
    read: false,
    created_at: iso(8 * 60000),
  },
  {
    notification_id: 5003,
    account_key: null,
    category: "SYSTEM",
    severity: "WARNING",
    title: "TradeLocker reconnect",
    message: "Lost session to MFF-Live. Reconnected after 14s.",
    metadata: {},
    read: false,
    created_at: iso(35 * 60000),
  },
  {
    notification_id: 5004,
    account_key: "trader1@example.com:48721",
    category: "MANAGEMENT",
    severity: "INFO",
    title: "Breakeven set",
    message: "XAUUSD #9002 SL moved to entry after TP1.",
    metadata: {},
    read: true,
    created_at: iso(2 * 3600000),
  },
  {
    notification_id: 5005,
    account_key: null,
    category: "SIGNAL",
    severity: "INFO",
    title: "Signal received: APEX-2411",
    message: "BUY GBPJPY @ 198.245 SL 197.8 TP 199.1",
    metadata: {},
    read: true,
    created_at: iso(50 * 60000),
  },
];

export const mockBotStatus: BotStatus = {
  status: "running",
  dry_run: false,
  active_accounts: 2,
  paused_accounts: 1,
  breached_accounts: 1,
  total_active_trades: 3,
  allow_weekend_trading: false,
  allow_eod_trading: true,
};