// File generated by FlutterFire CLI.
// Mirror Pupil Firebase Configuration
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjxKQJFeRdFwHMYybKcNer5QQHp2nVUz8',
    appId: '1:2009963821:web:d1dc6133ae10a1fc8747a4',
    messagingSenderId: '2009963821',
    projectId: 'mirror-pupil',
    authDomain: 'mirror-pupil.firebaseapp.com',
    storageBucket: 'mirror-pupil.firebasestorage.app',
    measurementId: 'G-GNS6TYCQCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl0qkRtlFLLKugwu6qTWXRF5suZj0cRos',
    appId: '1:2009963821:android:fd5b9bd344ecf9448747a4',
    messagingSenderId: '2009963821',
    projectId: 'mirror-pupil',
    storageBucket: 'mirror-pupil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjxKQJFeRdFwHMYybKcNer5QQHp2nVUz8',
    appId: '1:2009963821:ios:PLACEHOLDER',  // Replace with actual iOS app ID from Firebase Console
    messagingSenderId: '2009963821',
    projectId: 'mirror-pupil',
    storageBucket: 'mirror-pupil.firebasestorage.app',
    iosClientId: 'PLACEHOLDER.apps.googleusercontent.com',  // Replace with actual iOS client ID
    iosBundleId: 'com.example.mirrorpupil',  // Replace with your bundle ID
  );
}
